name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1
      EKS_CLUSTER_NAME: provablemarkets-mineks-cluster
      DOCKERHUB_USERNAME: rodrigorras

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/provablemarkets-demo:latest .

      # 4. Run tests inside the container
      - name: Run tests
        run: |
          docker run --rm $DOCKERHUB_USERNAME/provablemarkets-demo:latest python -m pytest tests_simple.py

      # 5. Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push $DOCKERHUB_USERNAME/provablemarkets-demo:latest

      # 6. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3  # Updated to v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}  # Fixed region reference

      # 7. Set up kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.33.0'

      # 8. Update kubeconfig to connect to EKS
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

      # 9. Deploy using Helm
      - name: Deploy with Helm
        run: |
          helm upgrade --install my-provablemarkets ./charts --namespace default
