name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  EKS_CLUSTER_NAME: provablemarkets-mineks-cluster
  DOCKERHUB_USERNAME: rodrigorras

jobs:
  # ----------------------------
  # Stage 1: Build and Test
  # ----------------------------
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set IMAGE_TAG
        id: set_tag
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "::set-output name=IMAGE_TAG::$IMAGE_TAG"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/provablemarkets-demo:$IMAGE_TAG .

      - name: Run tests inside container
        run: |
          docker run --rm $DOCKERHUB_USERNAME/provablemarkets-demo:$IMAGE_TAG python -m pytest tests_simple.py -v

  # ----------------------------
  # Stage 2: Push Docker image
  # ----------------------------
  push:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Set IMAGE_TAG from build
        run: echo "IMAGE_TAG=${{ needs.build-and-test.outputs.image_tag }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push $DOCKERHUB_USERNAME/provablemarkets-demo:$IMAGE_TAG

  # ----------------------------
  # Stage 3: Helm deploy
  # ----------------------------
  helm-deploy:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set IMAGE_TAG from build
        run: echo "IMAGE_TAG=${{ needs.build-and-test.outputs.image_tag }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.33.0'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install my-provablemarkets ./charts \
            --namespace default \
            --set image.tag=$IMAGE_TAG
