name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: rodrigorras

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set IMAGE_TAG (first 8 chars of SHA)
      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      # 3. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          echo "Using image tag: $IMAGE_TAG"
          docker build -t $DOCKERHUB_USERNAME/provablemarkets-demo:$IMAGE_TAG .

      # 5. Run tests
      - name: Run tests inside container
        run: |
          docker run --rm $DOCKERHUB_USERNAME/provablemarkets-demo:$IMAGE_TAG \
            python -m pytest tests_simple.py -v

  push:
    runs-on: ubuntu-latest
    needs: build-and-test  # only runs if build-and-test succeeds
    env:
      DOCKERHUB_USERNAME: rodrigorras

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push $DOCKERHUB_USERNAME/provablemarkets-demo:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: push  # only runs if push succeeds
    env:
      AWS_REGION: eu-central-1
      EKS_CLUSTER_NAME: provablemarkets-mineks-cluster
      DOCKERHUB_USERNAME: rodrigorras

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.33.0'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install my-provablemarkets ./charts \
            --namespace default \
            --set image.tag=$IMAGE_TAG
