name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # ---------------------------
  # Build, Test, Push
  # ---------------------------
  build-test-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: rodrigorras

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set IMAGE_TAG from commit SHA (8 chars)
      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      # 3. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          echo "Using image tag: $IMAGE_TAG"
          docker build -t $DOCKERHUB_USERNAME/provablemarkets-demo:$IMAGE_TAG .

      # 5. Run tests inside container
      - name: Run tests
        run: |
          docker run --rm $DOCKERHUB_USERNAME/provablemarkets-demo:$IMAGE_TAG \
            python -m pytest tests_simple.py -v

      # 6. Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push $DOCKERHUB_USERNAME/provablemarkets-demo:$IMAGE_TAG

      # 7. Save IMAGE_TAG for next jobs
      - name: Export IMAGE_TAG
        run: echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

  # ---------------------------
  # Deploy to EKS with Helm
  # ---------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build-test-push   # only runs if build+test+push succeeds
    env:
      AWS_REGION: eu-central-1
      EKS_CLUSTER_NAME: provablemarkets-mineks-cluster
      DOCKERHUB_USERNAME: rodrigorras

    steps:
      # 1. Checkout code (needed for Helm charts)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Restore IMAGE_TAG from previous job
      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      # 3. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 4. Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.33.0'

      # 5. Update kubeconfig for EKS
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

      # 6. Deploy with Helm (forces update with new tag)
      - name: Deploy with Helm
        run: |
          helm upgrade --install my-provablemarkets ./charts \
            --namespace default \
            --set image.repository=$DOCKERHUB_USERNAME/provablemarkets-demo \
            --set image.tag=$IMAGE_TAG
